[
  ./default-exec.nix
  ./docker-compose-service.nix
  ./extended-info.nix
  ./host-store.nix
  ./context.nix
  ./image.nix
  ./image-recommended.nix
  ./nixos.nix
  ./nixos-init.nix
  ../lib/assert.nix
  ./check-sys_admin.nix
]
