[
    ./modules/composition/docker-compose.nix
    ./modules/composition/host-environment.nix
    ./modules/composition/images.nix
    ./modules/composition/service-info.nix
    ./modules/composition/composition.nix
    ./modules/composition/deployment.nix
    ./modules/composition/deployment/docker.nix
    ./modules/composition/deployment/podman.nix
]
